### PR TITLE
Create CropperFinance

### PR DESCRIPTION
**Pull request by CropperFinance**
CropperFinance is The First Permissionless Yield Farming on Solana, enabling SPL projects builders to connect their liquidity to the platform, set up the total supply that will be allocated to farming, decide the weekly emission schedule and launch their yield farming in a few clicks.

### CODE REVIEW

**Comment by rmshea** [comment]
@CropperFinance can you fill out the description of your file here? otherwise, this looks good!

**Comment by CropperFinance** [comment]
> @CropperFinance can you fill out the description of your file here? otherwise, this looks good!

Hello rmshea, it's done :)

**Comment by CropperFinance** [comment]
<

> @CropperFinance can you fill out the description of your file here? otherwise, this looks good!

Hello rmshea, Added a brief description, hope this meets your expectations :)

**Comment by rmshea** [comment]
perfect, thank you! @CropperFinance

**Pull request merged**
