### PR TITLE
add Carecoin

### PR DESCRIPTION
**Pull request by carecointoken**

### CODE REVIEW

**Review by federaa — CHANGES_REQUESTED** [review]
Please submit a project logo CARECOIN.svg with this PR

**Comment by carecointoken** [comment]
[](url)

**Comment by carecointoken** [comment]
https://github.com/carecointoken/ecosystem/blob/master/img/CARECOIN

**Comment by carecointoken** [comment]
https://github.com/carecointoken/ecosystem/blob/c9622a12911bda16a4939fbfdadbcc5026552edd/img/CARECOIN.svg

**Comment by rmshea** [comment]
@carecointoken that is a different branch, please move that file to `carecointoken:patch-1`

**Comment by carecointoken** [comment]
im confused, can you help us? @rmshea, sorry for tagging and distrubing your time

**Pull request merged**
