### PR TITLE
Create NFTees.svg

### PR DESCRIPTION
**Pull request by SolNFTees**
Upload following jpg as logo 
NFTees
g

### CODE REVIEW

**Comment by SolNFTees** [comment]
slug: “NFTees”
date: “2021-09-22”
title: “NFTees”
logline: “A CommuniTee of 100 NFTees”
cta: “https://nftees.holaplex.com/#/”
logo: 
category: nft
status: live 
website: “https://nftees.holaplex.com/#/artworks”
twitter: “https://twitter.com/Sol_NFTees”
discord: “https://discord.gg/p9TNePvqZY”

**Comment by SolNFTees** [comment]
slug: “NFTees”
date: “2021-09-22”
title: “NFTees”
logline: “A CommuniTee of 100 NFTees”
cta: “https://nftees.holaplex.com/#/”
logo: 
category: nft
status: live 
website: “https://nftees.holaplex.com/#/artworks”
twitter: “https://twitter.com/Sol_NFTees”
discord: “https://discord.gg/p9TNePvqZY”

**Comment by SolNFTees** [comment]
---
slug: “NFTees”
date: “2021-09-22”
title: “NFTees”
logline: “A CommuniTee of 100 NFTees”
cta: https://nftees.holaplex.com/#/
logo: 
category: nft
status: live 
website: https://nftees.holaplex.com/#/artworks
twitter: https://twitter.com/Sol_NFTees
discord: https://discord.gg/p9TNePvqZY
---

A CommuniTee of 100 NFTees. Our mission is to create a tight knit, Solana NFT-focused community, where all individuals (Sol maxis, Artists, Collectors, Devs, Newbies and more) can connect, interact, and directly impact the Solana NFT ecosystem.

**Comment by rmshea** [comment]
@SolNFTees please try again, the file needs to be added to the actual repo, not linked here.

**Pull request closed without merging**
